
object Version {
    const val coreKtx = "1.9.0"
    const val compose = "1.6.0-alpha02"
    const val composeCompiler = "1.5.1"
    const val activityCompose = "1.7.0"
    const val constrainCompose = "1.0.1"
    const val lifecycleRuntime = "2.6.1"
    const val coroutine = "1.7.3"
    const val material3 = "1.1.1"
    const val material = "1.6.0-alpha02"
    const val daggerHilt = "2.46.1"
    const val destination = "1.9.42-beta"
    const val room_version = "2.5.2"
    const val datastore_version = "1.0.0"
    const val paging3 = "3.1.1"
    const val jUnit = "4.13.2"
    const val jUnitAndroid = "1.1.5"
    const val espresso = "3.4.0"
    const val retrofit = "2.9.0"
}